name: Retail Analytics CI-CD

on:

  push:
    branches:
      - develop
      - test
      - main

  pull_request:
    branches:
      - develop
      - test
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Repository Structure
        run: |
          python tests/run_tests.py

  test-databricks-connection:

    needs: validate

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Test Databricks Connection
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host=$DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token=$DATABRICKS_TOKEN" >> ~/.databrickscfg

          databricks workspace mkdirs /Workspace/Users/mohan.r@diggibyte.com/GitHub_CICD_Test

  deploy-test:

    if: github.ref == 'refs/heads/test'

    needs: test-databricks-connection

    runs-on: ubuntu-latest

    steps:

      - name: Trigger TEST Deployment Job

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host=$DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token=$DATABRICKS_TOKEN" >> ~/.databrickscfg

          databricks jobs run-now \
          --job-id 410916099611846

  deploy-prod:

    if: github.ref == 'refs/heads/main'

    needs: test-databricks-connection

    runs-on: ubuntu-latest

    steps:

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Trigger PROD Deployment Job

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host=$DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token=$DATABRICKS_TOKEN" >> ~/.databrickscfg

          databricks jobs run-now \
          --job-id 499793457618558
