name: Retail Analytics CI-CD

on:

  push:
    branches:
      - develop
      - test
      - main

  pull_request:
    branches:
      - develop
      - test
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Repository Structure
        run: |

         python tests/run_tests.py

  deploy-test:

    if: github.ref == 'refs/heads/test'

    needs: validate

    runs-on: ubuntu-latest

    steps:

      - name: Deploy To TEST
        run: |

          echo "Deploying Retail Analytics Pipeline To TEST"

  deploy-prod:

    if: github.ref == 'refs/heads/main'

    needs: validate

    runs-on: ubuntu-latest

    steps:

      - name: Deploy To PROD
        run: |

          echo "Deploying Retail Analytics Pipeline To PROD"
